services:
  matter-backend:
    image: gravitycloud/matter:latest
    container_name: matter-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GITHUB_ORG_TOKEN=<github-org-token>
      - GITHUB_ORG_NAME=<github-org-name>
      - AI_API_KEY=<open-ai-api-key>
      - AI_MODEL=<open-ai-model>
      - AI_PROVIDER=openai
      - ENABLE_PR_REVIEW_COMMENT=true
      - ENABLE_PR_DESCRIPTION=true
      - GRAVITY_API_KEY=<gravity-api-key>
    depends_on:
      - postgres
    networks:
      - matter-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:latest
    container_name: postgres-matter
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - matter-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  matter-network:
    driver: bridge

volumes:
  postgres-data: